import crypto from 'node:crypto';
import { HttpError } from '../../utils/http-error.js';
import { generateUlid } from '../../utils/ulid.js';
import {
  findCaseById,
  findCaseByRef,
  findCaseEventsByCaseId
} from '../recovery/case.repository.js';
import { findTracesByCaseId } from '../ai/tracing/trace.service.js';
import type { CaseEvent, RecoveryCase } from '../recovery/case.types.js';
import type { AgentTrace } from '../ai/tracing/trace.types.js';
import type {
  AuditExportFormat,
  CaseAuditExportData,
  ExportAuditOptions
} from './audit.types.js';

/**
 * Computes a deterministic SHA-256 cryptographic signature over the canonical audit trail data.
 */
export function computeAuditSignature(
  caseData: RecoveryCase,
  events: CaseEvent[],
  traces: AgentTrace[],
  generatedAt: string
): string {
  const canonicalPayload = JSON.stringify({
    caseId: caseData.id,
    caseRef: caseData.caseRef,
    merchantId: caseData.merchantId,
    status: caseData.status,
    recoverableAmount: caseData.recoverableAmount,
    currency: caseData.currency,
    events: events.map((e) => ({
      id: e.id,
      fromStatus: e.fromStatus,
      toStatus: e.toStatus,
      actorType: e.actorType,
      actorId: e.actorId,
      reason: e.reason,
      payload: e.payload,
      createdAt: e.createdAt
    })),
    traces: traces.map((t) => ({
      traceRef: t.traceRef,
      agentType: t.agentType,
      status: t.status,
      totalDurationMs: t.totalDurationMs
    })),
    generatedAt
  });

  return crypto.createHash('sha256').update(canonicalPayload, 'utf8').digest('hex');
}

/**
 * Escapes a field for RFC 4180 compliant CSV formatting.
 */
function escapeCsvField(value: unknown): string {
  if (value === null || value === undefined) {
    return '';
  }
  const str = typeof value === 'object' ? JSON.stringify(value) : String(value);
  if (str.includes(',') || str.includes('"') || str.includes('\n') || str.includes('\r')) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

/**
 * Compiles full case audit history for a merchant.
 */
export async function compileCaseAuditData(
  idOrRef: string | number,
  merchantId: number,
  actorEmail: string,
  options: ExportAuditOptions = {}
): Promise<CaseAuditExportData> {
  // 1. Resolve case with strict tenant isolation (Invariant I9)
  const recoveryCase =
    typeof idOrRef === 'number' || /^\d+$/.test(String(idOrRef))
      ? await findCaseById(Number(idOrRef), merchantId)
      : await findCaseByRef(String(idOrRef), merchantId);

  if (!recoveryCase) {
    throw new HttpError(404, 'CASE_NOT_FOUND', `Recovery case '${idOrRef}' not found.`);
  }

  // 2. Fetch chronological case events (RDB-002 / AUD-001)
  const events = await findCaseEventsByCaseId(recoveryCase.id, merchantId);

  // 3. Fetch agent traces (AI-007) if requested or by default
  const traces = options.includeTraces !== false
    ? await findTracesByCaseId(recoveryCase.id, merchantId)
    : [];

  const generatedAt = new Date().toISOString();
  const exportId = `EXP_${generateUlid()}`;
  const integritySignature = computeAuditSignature(recoveryCase, events, traces, generatedAt);

  return {
    metadata: {
      exportId,
      generatedAt,
      generatedBy: actorEmail,
      merchantId,
      caseId: recoveryCase.id,
      caseRef: recoveryCase.caseRef,
      integritySignature,
      eventCount: events.length,
      traceCount: traces.length
    },
    case: recoveryCase,
    events,
    traces
  };
}

/**
 * Formats audit data into RFC 4180 CSV representation.
 */
export function formatAuditAsCsv(auditData: CaseAuditExportData): string {
  const lines: string[] = [];

  // CSV metadata header comments
  lines.push(`# PayBridge AI — Certified Case Audit Trail Export (AUD-006)`);
  lines.push(`# Export ID: ${auditData.metadata.exportId}`);
  lines.push(`# Generated At: ${auditData.metadata.generatedAt}`);
  lines.push(`# Generated By: ${auditData.metadata.generatedBy}`);
  lines.push(`# Merchant ID: ${auditData.metadata.merchantId}`);
  lines.push(`# Case Ref: ${auditData.metadata.caseRef} (ID: ${auditData.metadata.caseId})`);
  lines.push(`# Status: ${auditData.case.status}`);
  lines.push(`# Recoverable Value: ${auditData.case.recoverableAmount} ${auditData.case.currency}`);
  lines.push(`# Integrity Checksum (SHA-256): ${auditData.metadata.integritySignature}`);
  lines.push('');

  // Table header
  const headers = [
    'event_id',
    'timestamp',
    'case_id',
    'case_ref',
    'actor_type',
    'actor_id',
    'from_status',
    'to_status',
    'reason',
    'payload',
    'correlation_id'
  ];
  lines.push(headers.join(','));

  // Event rows
  for (const event of auditData.events) {
    const row = [
      escapeCsvField(event.id),
      escapeCsvField(event.createdAt),
      escapeCsvField(event.caseId),
      escapeCsvField(auditData.case.caseRef),
      escapeCsvField(event.actorType),
      escapeCsvField(event.actorId),
      escapeCsvField(event.fromStatus),
      escapeCsvField(event.toStatus),
      escapeCsvField(event.reason),
      escapeCsvField(event.payload),
      escapeCsvField(event.correlationId)
    ];
    lines.push(row.join(','));
  }

  return lines.join('\r\n');
}

/**
 * Exports case audit trail as either CSV or JSON.
 */
export async function exportCaseAuditTrail(
  idOrRef: string | number,
  merchantId: number,
  actorEmail: string,
  format: AuditExportFormat = 'csv',
  includeTraces: boolean = true
): Promise<{
  content: string;
  contentType: string;
  filename: string;
  signature: string;
  data: CaseAuditExportData;
}> {
  const auditData = await compileCaseAuditData(idOrRef, merchantId, actorEmail, {
    format,
    includeTraces
  });

  const timestamp = auditData.metadata.generatedAt.replace(/[:.]/g, '-');
  const signature = auditData.metadata.integritySignature;

  if (format === 'json') {
    return {
      content: JSON.stringify(auditData, null, 2),
      contentType: 'application/json; charset=utf-8',
      filename: `audit-case-${auditData.case.caseRef}-${timestamp}.json`,
      signature,
      data: auditData
    };
  }

  const csvContent = formatAuditAsCsv(auditData);
  return {
    content: csvContent,
    contentType: 'text/csv; charset=utf-8',
    filename: `audit-case-${auditData.case.caseRef}-${timestamp}.csv`,
    signature,
    data: auditData
  };
}
